#!/usr/bin/env node
/**
 * UX acceptance harness.
 *
 * Every criterion the transformation committed to, measured in one place and enforced
 * with an exit code. This exists because the same figures were measured by hand three
 * times and two of them came back wrong: a greedy regex over `sr-only` captured nested
 * markup and reported 5 158 and then 4 176 characters where the real number was 1 226.
 * A measurement nobody can re-run is an opinion.
 *
 * Static checks read the source tree. Payload checks read the prerendered HTML, so
 * `npm run build` must have run first. Anything needing a live layout (mobile geometry,
 * computed contrast of a painted control) is out of scope here and is checked in the
 * browser — this harness never claims to have verified those.
 *
 * Node stdlib only.
 */

import { readFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, relative } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const results = [];
let failed = 0;

function check(name, actual, pass, expected) {
  results.push({ name, actual, pass, expected });
  if (!pass) failed += 1;
}

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    if (entry === "node_modules" || entry === ".next" || entry === ".git") continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

const sourceFiles = walk(join(root, "app"))
  .concat(walk(join(root, "components")))
  .concat(walk(join(root, "lib")))
  .filter((f) => f.endsWith(".tsx") || f.endsWith(".ts"));

const read = (f) => readFileSync(f, "utf8");
const allSource = sourceFiles.map(read).join("\n");
const css = read(join(root, "app", "globals.css"));

// ── 1. Token system ──────────────────────────────────────────────────────────
const inlineStyles = (allSource.match(/style=\{\{/g) || []).length;
check("inline style={{}} objects", inlineStyles, inlineStyles < 15, "< 15 (was 76)");

// Tokens declared in the :root blocks that nothing references. Scoped to :root on
// purpose: names inside @theme / @theme inline are Tailwind's utility-generation
// bridge, consumed by the compiler rather than by var(), and counting them as dead
// was this harness's own first false positive.
const rootBlocks = [...css.matchAll(/:root\s*\{([^}]*)\}/g)].map((m) => m[1]).join("\n");
const declared = new Set([...rootBlocks.matchAll(/(--[a-z0-9-]+):/g)].map((m) => m[1]));
const deadTokens = [...declared].filter((tok) => {
  const uses = (allSource.match(new RegExp(`var\\(${tok}\\)`, "g")) || []).length;
  const cssUses = (css.match(new RegExp(`var\\(${tok}\\)`, "g")) || []).length;
  // A token consumed only by the @theme inline bridge still needs a utility consumer.
  return uses + cssUses === 0;
});
check("dead :root tokens", deadTokens.length, deadTokens.length === 0, `0 — ${deadTokens.join(", ") || "none"}`);

// Utilities generated by @theme inline that no className uses.
const themeInline = css.slice(css.indexOf("@theme inline"), css.indexOf("}", css.indexOf("@theme inline")));
const colorUtils = [...themeInline.matchAll(/--color-([a-z-]+):/g)].map((m) => m[1]);
const unusedUtils = colorUtils.filter((u) => {
  const re = new RegExp(`(?:bg|text|border|fill|stroke)-${u}(?![a-z-])`, "g");
  return !(allSource.match(re) || []).length;
});
check(
  "unused @theme utilities",
  unusedUtils.length,
  unusedUtils.length === 0,
  `0 — ${unusedUtils.join(", ") || "none"}`,
);

const arbitrarySizes = [...new Set((allSource.match(/text-\[\d+px\]/g) || []))];
check("arbitrary font sizes", arbitrarySizes.length, arbitrarySizes.length === 0, `0 — ${arbitrarySizes.join(" ")}`);

const scaleSizes = new Set((allSource.match(/\btext-(2xs|xs|sm|base|md|lg|xl|2xl|3xl)\b/g) || []));
check("distinct font sizes", scaleSizes.size, scaleSizes.size <= 10, "<= 10 (was 13)");

// ── 2. Legacy tokens must be fully retired ───────────────────────────────────
const legacy = ["--muted", "--paper", "--paper-sunk", "--ink", "--rule", "--amber", "--amber-soft"];
const legacyRefs = legacy.filter((t) => allSource.includes(`var(${t})`));
check("undefined legacy token refs", legacyRefs.length, legacyRefs.length === 0, `0 — ${legacyRefs.join(", ") || "none"}`);

// ── 3. Accessibility, statically checkable ───────────────────────────────────
// Selected state must not be painted off an ARIA attribute.
const ariaStyled = /\[aria-pressed="true"\]\s*[,{]/.test(css);
check("selected state styled via ARIA attr", ariaStyled ? "yes" : "no", !ariaStyled, "no (use a class)");

// Every horizontal scroller needs to be reachable by keyboard.
const scrollerFiles = sourceFiles.filter((f) => read(f).includes("overflow-x-auto"));
const badScrollers = [];
for (const f of scrollerFiles) {
  const src = read(f);
  for (const m of src.matchAll(/<div[^>]*overflow-x-auto[^>]*>/g)) {
    const tag = m[0];
    // The mobile metric strip contains its own focusable buttons, so focus can reach
    // and scroll it without the container being a tab stop. Anything wrapping a table
    // must be a tab stop itself.
    const selfFocusable = tag.includes("no-scrollbar");
    if (!selfFocusable && !tag.includes("tabIndex")) {
      badScrollers.push(`${relative(root, f)}: ${tag.slice(0, 60)}`);
    }
  }
}
check("scrollers without tabIndex", badScrollers.length, badScrollers.length === 0, `0 — ${badScrollers.join(" | ") || "none"}`);

// Hardcoded English in user-visible attributes/text.
const hardcoded = [];
for (const f of sourceFiles) {
  const src = read(f);
  for (const m of src.matchAll(/aria-label="([A-Z][^"]*)"/g)) {
    hardcoded.push(`${relative(root, f)}: aria-label="${m[1]}"`);
  }
}
check("hardcoded aria-labels", hardcoded.length, hardcoded.length === 0, `0 — ${hardcoded.join(" | ") || "none"}`);

// ── 4. i18n integrity ────────────────────────────────────────────────────────
const en = JSON.parse(read(join(root, "messages", "en.json")));
const es = JSON.parse(read(join(root, "messages", "es.json")));

function flatten(obj, prefix = "") {
  const out = [];
  for (const [k, v] of Object.entries(obj)) {
    const key = prefix ? `${prefix}.${k}` : k;
    if (v && typeof v === "object") out.push(...flatten(v, key));
    else out.push(key);
  }
  return out;
}
const enKeys = flatten(en);
const esKeys = flatten(es);
const onlyEn = enKeys.filter((k) => !esKeys.includes(k));
const onlyEs = esKeys.filter((k) => !enKeys.includes(k));
check("locale key parity", onlyEn.length + onlyEs.length, onlyEn.length + onlyEs.length === 0,
  `0 — en-only: ${onlyEn.join(",") || "none"} / es-only: ${onlyEs.join(",") || "none"}`);

// A key with no call site is copy written for a control nobody built.
//
// Keys composed at runtime (t(`link_${field}`), t(`formula.inputs_${category}`)) cannot
// be found by looking for the literal, so their prefixes are resolved from the template
// literals actually present in the source rather than hardcoded here — a hardcoded
// allowlist would silently keep covering a key after its call site was deleted.
// A call site names the key with its namespace already applied — `useTranslations
// ("methodology")` then `t("formula.body")` — so the literal in the source is some
// SUFFIX of the full dotted path, not the leaf and not the whole thing. Testing every
// suffix is what makes this precise; testing only the leaf reported 62 false positives.
const dynamicPrefixes = [...allSource.matchAll(/[`"']([a-zA-Z_.]+)\$\{/g)].map((m) => m[1]);
const literals = new Set(
  [...allSource.matchAll(/["'`]([a-zA-Z0-9_.]+)["'`]/g)].map((m) => m[1]),
);
const unusedKeys = enKeys.filter((full) => {
  if (/^(meta|masthead)\./.test(full)) return false;
  const parts = full.split(".");
  const suffixes = parts.map((_, i) => parts.slice(i).join("."));
  if (suffixes.some((s) => literals.has(s))) return false;
  // Composed at runtime, e.g. t(`link_${field}`) or t(`formula.inputs_${category}`).
  if (dynamicPrefixes.some((p) => suffixes.some((s) => s.startsWith(p)))) return false;
  return true;
});
check("i18n keys with no call site", unusedKeys.length, unusedKeys.length === 0,
  `0 — ${unusedKeys.slice(0, 12).join(", ") || "none"}`);

// ── 5. Payload, from the prerendered build ───────────────────────────────────
const htmlPath = join(root, ".next", "server", "app", "es.html");
if (!existsSync(htmlPath)) {
  console.log("Payload checks skipped: run `npm run build` first.\n");
} else {
  const html = read(htmlPath);
  check("prerendered document chars", html.length, html.length < 380000, "< 380 000 (was 441 013)");

  const rsc = [...html.matchAll(/__next_f\.push\(\[1,(.*?)\]\)/gs)].reduce((n, m) => n + m[1].length, 0);
  check("inline RSC payload chars", rsc, rsc < 110000, "< 110 000 (was 176 319)");

  // Nesting-aware: take each sr-only element's own text, not everything up to the
  // next closing tag of the same name. This is the bug that produced two wrong numbers.
  let srChars = 0;
  const srTexts = [];
  for (const m of html.matchAll(/<(span|h2|div|caption)[^>]*class="[^"]*\bsr-only\b[^"]*"[^>]*>/g)) {
    const tag = m[1];
    let depth = 1;
    let inner = "";
    const rest = html.slice(m.index + m[0].length);
    for (const t of rest.matchAll(new RegExp(`</?${tag}\\b[^>]*>`, "g"))) {
      depth += t[0].startsWith("</") ? -1 : 1;
      if (depth === 0) {
        inner = rest.slice(0, t.index);
        break;
      }
    }
    const text = inner.replace(/<[^>]+>/g, "");
    srChars += text.length;
    srTexts.push(text);
  }
  check("sr-only text chars", srChars, srChars < 4000, "< 4 000 (was 30 235)");
  check("sr-only unique strings", new Set(srTexts).size, new Set(srTexts).size < 26, "< 26 (was 26)");

  // Compared against data/models.json rather than a fixed literal: the daily ingest
  // (R8) changes the model count on its own schedule, unrelated to any UI change, so a
  // hardcoded expectation here would go stale on the next ingest regardless of whether
  // this harness still holds - the same reason the Python golden test rebuilds from the
  // versioned cache instead of asserting a fixed row count.
  const modelLinks = new Set([...html.matchAll(/\/model\/([a-z0-9.\-]+)"/g)].map((m) => m[1]));
  const { models: allModels } = JSON.parse(read(join(root, "data", "models.json")));
  check("model rows rendered", modelLinks.size, modelLinks.size === allModels.length,
    `${allModels.length} (data/models.json)`);

  const headings = (html.match(/<h[12]\b/g) || []).length;
  check("home headings (h1+h2)", headings, headings >= 4, ">= 4 (was 1)");
}

// ── 6. Invariants ────────────────────────────────────────────────────────────
const pkg = JSON.parse(read(join(root, "package.json")));
check("runtime dependencies", Object.keys(pkg.dependencies).length, Object.keys(pkg.dependencies).length === 5, "5 (unchanged)");
check("clsx imported", (allSource.match(/from "clsx"/g) || []).length > 0 ? "yes" : "no",
  (allSource.match(/from "clsx"/g) || []).length > 0, "yes (was a dependency with 0 imports)");

// ── Report ───────────────────────────────────────────────────────────────────
const width = Math.max(...results.map((r) => r.name.length));
console.log("UX acceptance harness\n");
for (const r of results) {
  console.log(
    `  ${r.pass ? "ok  " : "FAIL"}  ${r.name.padEnd(width)}  ${String(r.actual).padEnd(8)} ${r.pass ? "" : "expected " + r.expected}`,
  );
}
if (failed) {
  console.error(`\n${failed} criterion/criteria not met.`);
  process.exit(1);
}
console.log(`\nAll ${results.length} criteria met.`);
